---
- name: Batched SSH Port Check from Control Node
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    batch_size: 50
    report_filename: "ssh_connectivity_report_{{ lookup('ansible.builtin.timestamp', '%Y-%m-%dT%H-%M-%SZ', wantlist=true)[0] }}.csv"

  tasks:
    - name: "Initialize list for combined results"
      ansible.builtin.set_fact:
        combined_results: []

    - name: "Loop through host batches and process them"
      ansible.builtin.include_tasks: _process_batch.yml
      loop: "{{ groups['all'] | batch(batch_size) }}"
      loop_control:
        loop_var: host_batch
        label: "Batch {{ loop.index }} of {{ (groups['all']|length / batch_size)|round(0, 'ceil')|int }}"

    # --- FINAL REPORTING (runs after all batches are complete) ---
   # - name: "Assemble CSV content from combined results"
   #   ansible.builtin.set_fact:
   #     csv_content: |
    #      hostname,status
    #      {% for result in combined_results %}
    #      {{ result.item.item }},{{ 'SUCCESS' if not result.ansible_result.failed else 'FAILURE' }}
    #      {% endfor %}

    - name: "Calculate success and failure counts from combined results"
      ansible.builtin.set_fact:
        success_count: "{{ (combined_results | rejectattr('ansible_result', 'failed') | list) | length }}"
        failure_count: "{{ (combined_results | selectattr('ansible_result', 'failed') | list) | length }}"

    - name: "Display final summary and report location"
      ansible.builtin.debug:
        msg: >
          All batches complete.
          Total: {{ combined_results | length }},
          Success: {{ success_count }},
          Failure: {{ failure_count }}.
          Report generated at /tmp/{{ report_filename }}
