---
inventories:
  - name: "My Custom Script Inventory"
    description: "Inventory sourced from a custom Python script"
    sources:
      - name: "Custom Python Inventory Source"
        source: script # Use the script inventory source plugin
        source_vars:
          # This is the key to the solution.
          # We explicitly call python3 to run our script.
          command: "python3 multi_account_ec2_inventory.py"
